# Author: Johan Sydseter <johan.sydseter@startsiden.no>
---
autoinstallver: 1
name: vagrant-sydseter-debian-wheezy-amd64-puppet-ext
version: 13.02.01-01

exludeext:
  - .md
  - .git
  - .gitignore
  - .gitmodules

installto:
  doc: /usr/share/doc/vagrant-sydseter-debian-wheezy-amd64-puppet-ext
  t: /usr/share/doc/vagrant-sydseter-debian-wheezy-amd64-puppet-ext
  bin: /usr/local/bin

depends:
  - viritualbox
  - vagrant

excludedir:
  - utils

installdir: /usr/local/vagrant-sydseter-debian-wheezy-amd64-puppet-ext
tests: t/
test_requires:
  - viritualbox
  - vagrant
